### ISSUE TITLE
Clever-cloud can't start app

### ISSUE THREAD

**Issue by Nigui** [spacelephant/sonarplanet-services#6]
# Fact

Latest commit on develop branch doesn't start and crashes with the log : 

```
> sonarplanet-services@1.0.0 start /home/bas/app_3ede6099-7dfd-4c16-a4da-97249401da4c
2018-05-11T15:42:26+02:00 > node ./dist/app.js
2018-05-11T15:42:27+02:00 module.js:540
2018-05-11T15:42:27+02:00 throw err;
2018-05-11T15:42:27+02:00 Error: Cannot find module '/home/bas/app_3ede6099-7dfd-4c16-a4da-97249401da4c/dist/app.js'
2018-05-11T15:42:27+02:00 ^
2018-05-11T15:42:27+02:00 at Function.Module._load (module.js:468:25)
2018-05-11T15:42:27+02:00 at Function.Module._resolveFilename (module.js:538:15)
2018-05-11T15:42:27+02:00 at bootstrap_node.js:608:3
2018-05-11T15:42:27+02:00 at startup (bootstrap_node.js:187:16)
2018-05-11T15:42:27+02:00 at Function.Module.runMain (module.js:684:10)
2018-05-11T15:42:27+02:00 npm ERR! code ELIFECYCLE
2018-05-11T15:42:27+02:00 npm ERR! sonarplanet-services@1.0.0 start: `node ./dist/app.js`
2018-05-11T15:42:27+02:00 npm ERR! errno 1
2018-05-11T15:42:27+02:00 npm ERR! Exit status 1
2018-05-11T15:42:27+02:00 npm ERR! Failed at the sonarplanet-services@1.0.0 start script.
2018-05-11T15:42:27+02:00 npm ERR!
2018-05-11T15:42:27+02:00 npm ERR! /home/bas/.npm/_logs/2018-05-11T13_42_26_984Z-debug.log
2018-05-11T15:42:27+02:00 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
It seems that when clever-cloud runs `yarn start` it can't find `dist/app.js`.

# Reason

The reason is that clever-cloud is plugged to the `develop` and when new commit occurs, it's running : 
1. `yarn` (install dependencies)
2. `yarn start` (run node)
*[cf. doc](https://www.clever-cloud.com/doc/nodejs/nodejs)*

It's a normal behavior, because currently, in the develop branch, there is no `scripts.install`. It means that clever-cloud install dependencies but does not build project with typescript compiler. So, `./dist/apps.js` is not generated.

# Solutions

1. Wait the merge of PR #5 which contains the [install script](https://github.com/sonarplanet/sonarplanet-services/blob/ftreguer-restful-api/package.json#L47)
2. Rename the current [build script](https://github.com/sonarplanet/sonarplanet-services/blob/develop/package.json#L16) to `install` to make develop deployable on clever-cloud.
3. Add a [custom run command](https://www.clever-cloud.com/doc/nodejs/nodejs/#custom-run-command) calling `build` script before `start` script.

**Comment by Nigui** [comment]
- solution 1 seems`quick & dirty` 
- solution 2 seems `costly & clean`
- solution 3 seems `costly & dirty`

**Comment by Nigui** [comment]
Solution 3 adopted. 

Add `CC_POST_BUILD_HOOK=yarn build` in environment variables
